python ./video_sci_proxgrad_multiGPU.py \
--batch_size 3 \
--lr 0.00001 \
--lr_gamma 0.1 \
--sched_step 10 \
--print_every_n_steps 10 \
--save_every_n_steps 100 \
--savepath ./save/dncnn_exp4/ \
--trainpath ../../data/DAVIS/matlab/ \
--testpath ../../data/test_gray/ \
--loadpath ./save/dncnn_exp3/model/best.ckpt \
--denoiser DnCNN \
--gpu_ids 7
