python ./video_sci_proxgrad_multiGPU.py \
--batch_size 1 \
--lr 0.0001 \
--lr_gamma 0.1 \
--sched_step 10 \
--print_every_n_steps 100 \
--save_every_n_steps 1000 \
--savepath ./save/ffdnet_exp0/ \
--trainpath ../data/DAVIS/matlab/ \
--testpath ../data/test_gray/ \
--loadpath ./save/test_ffdnet/model/best.ckpt \
--denoiser ffdnet \
--gpu_ids 0
