python ./video_sci_proxgrad_multiGPU.py \
--batch_size 4 \
--lr 0.0001 \
--lr_gamma 0.1 \
--sched_step 10 \
--print_every_n_steps 10 \
--save_every_n_steps 500 \
--savepath ./save/unetnorm_noise_exp0/ \
--trainpath ../../data/DAVIS/matlab/ \
--testpath ../../data/test_gray/ \
--loadpath None \
--denoiser unetnorm_noise \
--gpu_ids 8